In [28]:
from diffrax import diffeqsolve, ODETerm, Dopri5, SaveAt
import jax.numpy as jnp
import jax
from jax import jit

In [2]:
def f(t, y, args):
    return -y

In [35]:
term = ODETerm(f)
solver = Dopri5()
# saveat = SaveAt(ts=[0., 1., 2., 3.])
saveat = SaveAt(ts=jnp.linspace(0,5,5))

In [68]:
y0 = jnp.array([2.0, 3.0]).reshape(-1,1)
solution = diffeqsolve(term, solver, t0=0, t1=31, dt0=0.1, y0=y0, saveat=saveat)

In [65]:
solution.ys

Array([[2.        , 3.        ],
       [0.5730095 , 0.8595144 ],
       [0.16416995, 0.2462549 ],
       [0.04703546, 0.07055321],
       [0.01347589, 0.02021383]], dtype=float32, weak_type=True)

In [71]:
solution.ys

Array([[[2.        ],
        [3.        ]],

       [[0.57300955],
        [0.8595146 ]],

       [[0.16417   ],
        [0.24625498]],

       [[0.04703548],
        [0.07055323]],

       [[0.0134759 ],
        [0.02021384]]], dtype=float32, weak_type=True)

In [8]:
y0 = jnp.array([3.0])
solution2 = diffeqsolve(term, solver, t0=0, t1=3.7, dt0=0.1, y0=y0)

In [20]:
%timeit diffeqsolve(term, solver, t0=0, t1=3.7, dt0=0.1, y0=y0)

64 µs ± 382 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
solution2.ys

Array([[0.07417057]], dtype=float32, weak_type=True)

In [56]:
# @jit
def solve(t0, t1, dt0, y0, saveat):
    solution = diffeqsolve(term, solver, t0=t0, t1=t1, dt0=dt0, y0=y0, saveat = SaveAt(ts=saveat))
    return solution.ys

In [57]:
%timeit solve(t0=0, t1=6.0, dt0=0.1, y0=y0, saveat=jnp.linspace(0,5,6))

131 µs ± 286 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Diffrax FF-CBF

In [59]:
jnp.linspace(0, 2.0, int(2.0/0.5)+1)

Array([0. , 0.5, 1. , 1.5, 2. ], dtype=float32)

In [72]:
a = jnp.array([ [1,2],[3,4] ])

In [75]:
s = jnp.sum(a, axis=0)

In [76]:
jnp.min(s)

Array(4, dtype=int32)

In [78]:
b = jnp.array([[1],[2]])

In [82]:
ts = jnp.linspace(0, 6, int(1.0/0.5)+1)


Array([0., 3., 6.], dtype=float32)

In [84]:
b * ts

Array([[ 0.,  3.,  6.],
       [ 0.,  6., 12.]], dtype=float32)